version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"  # Adjust this according to your project structure
    schedule:
      interval: "daily"  # Adjust the update frequency as needed
      
